apiVersion: v2
name: nsq
description: A realtime distributed messaging platform
type: application
version: 0.0.5
appVersion: 1.2.1
home: https://github.com/nsqio/helm-chart/tree/master/charts/nsq
icon: https://nsq.io/static/img/nsq_blue.png
keywords:
- nsq
- nsqd
- nsqlookupd
- nsqadmin
maintainers:
- email: benhu@beeinventor.com
  name: BeeInventor
sources:
- https://github.com/nsqio/helm-chart/tree/master/charts/nsq
- https://nsq.io/
